### ISSUE TITLE
1주차 -> 1장, 2장

### ISSUE THREAD

**Issue by cloudwi** [cloudwi/HTTP_The_Definitive_Guide_Stduy#1]

**Comment by cloudwi** [comment]
### 장주영 1장 ~ 2장 자료(https://curious-watcher-814.notion.site/1-2-aa5240121c9a4830a0df5744fee95246)

**Comment by ybkim-dev** [comment]
[김영빈 1장 ~ 2장](https://khuybi87.notion.site/Http-1-2-f7eccfa3cff84d6cb350ca77736ac232)

**Comment by cloudwi** [comment]
[장주영 1장 ~ 2장](https://curious-watcher-814.notion.site/1-2-aa5240121c9a4830a0df5744fee95246)

**Comment by kivv00ng** [comment]
[김기웅 1장 ~ 2장](https://kivv00ng.notion.site/01-HTTP-02-URL-428de98153da4c65bb9f3632d8c9136b)

**Comment by yeeeze** [comment]
[장예지 1장 ~ 2장](https://velog.io/@yeezze/telnet을-이용한-HTTP-원격-접속)
읽고 흥미로운 부분 실습을 따라했습니다!

**Comment by Albatross3** [comment]
[이동준 1장](https://angry-bit-10d.notion.site/01-HTTP-4cfa4dfcecb64a7da99236d7cf4930ad)
[이동준 2장](https://angry-bit-10d.notion.site/02-URL-892d628767374d40b1d5d001784d86c4)

**Comment by cloudwi** [comment]
수빈 서브멘토님 [http  인코딩, 디코딩](https://blog.naver.com/pruvia7615/222676957056)
