### ISSUE TITLE
2주차 -> 3장

### ISSUE THREAD

**Issue by cloudwi** [cloudwi/HTTP_The_Definitive_Guide_Stduy#2]

**Comment by ybkim-dev** [comment]
[김영빈 3장](https://khuybi87.notion.site/Http-3-17911e4f923748d8a6926cc1b05a3fa6)

**Comment by cloudwi** [comment]
[장주영 3장](https://www.notion.so/3-623efcc3bfee4499aba46f0ceb0a98ab)

**Comment by kivv00ng** [comment]
[김기웅 3장](https://kivv00ng.notion.site/03-HTTP-f75c6fa851d44bc6abb93eae12c938f7)

**Comment by cloudwi** [comment]
문제점

- TRACE는 중간 애플리케이션이 여러 다른 종류의 요청들을 일관되게 다룬다고 가정하는 문제가 있다.
- TRACE 요청은 어떠한 엔터티 본문도 보낼 수 없다. TRACE 응답의 엔터티 본문에는 서버가 받은 요청이 그래도 들어있다.

**Comment by yeeeze** [comment]
[장예지 3장](https://velog.io/@yeezze/HTTP-완벽가이드-3장-HTTP-메시지)

**Comment by Albatross3** [comment]
[이동준 3장](https://angry-bit-10d.notion.site/03-HTTP-b41bbdc4b41342a29b79c33e658b1467)
