### ISSUE TITLE
4장

### ISSUE THREAD

**Issue by cloudwi** [cloudwi/HTTP_The_Definitive_Guide_Stduy#3]

**Comment by kivv00ng** [comment]
[김기웅 4장](https://kivv00ng.notion.site/04-b2be7da571314a809cdd3be5449f4d5f)

**Comment by cloudwi** [comment]
[장주영 4장](https://www.notion.so/4-311f28c3827946d7a0511ed3d228d862)

**Comment by ybkim-dev** [comment]
[김영빈 4장](https://khuybi87.notion.site/Http-4-8f3ad947763747e89bfce643057c3714)

**Comment by Albatross3** [comment]
[4장 이동준](https://angry-bit-10d.notion.site/04-b146f9602a72457dbc10c5d9abd75b2e)
