### ISSUE TITLE
5,6장

### ISSUE THREAD

**Issue by ybkim-dev** [cloudwi/HTTP_The_Definitive_Guide_Stduy#4]

**Comment by ybkim-dev** [comment]
[김영빈 5,6장](https://khuybi87.notion.site/Http-5-6-3aac9fa38e70411a9b0073cb81e71496)

**Comment by kivv00ng** [comment]
[김기웅 5,6장](https://kivv00ng.notion.site/05-06-24c7e89494364c5e8cab558643b18ee7)
